### ISSUE TITLE
"*-email-*"

### ISSUE THREAD

**Issue by stevenvachon** [codsen/posthtml-email-remove-unused-css#2]
Why have "email" in the project name?

**Comment by revelt** [comment]
Because this library works only on pages that have embedded CSS in head styles, no external stylesheets and no JS tinkering with dynamic CSS — that's 100% of email templates and maybe 0.001% of web pages. I don't want to position this library as a competitor for UnCSS and likes.

Additionally, the mindset is email template-oriented: both classes and id's are treated equally, both can be whitelisted, removed and will be reported in the same lists (removed from head/removed from body). That's not a big deal, but competitor libraries overlook id's since they are frowned upon in web dev. Not so in email — major CSS hack for Outlook 2010 is `#outlook` for example.

Are you thinking it should be changed?

**Comment by stevenvachon** [comment]
You're already differentiated from uncss by using posthtml instead of a headless browser. Even at 0.001%, it's still a possibility.

I just think that the name is too long and specific, when it could be shorter and generalized.

**Comment by revelt** [comment]
But isn't it too late to change the name, it's on npm!?!

**Comment by stevenvachon** [comment]
If you wanted you could publish a new package and deprecate the old until its downloads are so low that you can have it removed from the system (via emailing npm).
